"""initial: create auction and lot tables

Revision ID: 0001
Revises: 
Create Date: 2026-04-05

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auctions',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'CLOSED', 'CANCELLED', name='auctionstatus'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auctions_status'), 'auctions', ['status'], unique=False)
    op.create_index(op.f('ix_auctions_user_id'), 'auctions', ['user_id'], unique=False)
    op.create_table('lots',
    sa.Column('auction_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('starting_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('min_bid_increment', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'SOLD', 'UNSOLD', 'CANCELLED', name='lotstatus'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('winner_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['auction_id'], ['auctions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lots_auction_id'), 'lots', ['auction_id'], unique=False)
    op.create_index(op.f('ix_lots_status'), 'lots', ['status'], unique=False)
    op.create_index(op.f('ix_lots_winner_id'), 'lots', ['winner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lots_winner_id'), table_name='lots')
    op.drop_index(op.f('ix_lots_status'), table_name='lots')
    op.drop_index(op.f('ix_lots_auction_id'), table_name='lots')
    op.drop_table('lots')
    op.drop_index(op.f('ix_auctions_user_id'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_status'), table_name='auctions')
    op.drop_table('auctions')
    # ### end Alembic commands ###
